apiVersion: v1
kind: Service
metadata:
  name: gcp-deployment-service
  labels:
    name: gcp-deployment-service
spec:
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: gcp-deployment-app
  type: LoadBalancer

